//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waats.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrainFitness
    {
        public int BrainFitnessID { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> MarkAsCompleted { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<int> StartingNumber { get; set; }
        public Nullable<int> Q_Add { get; set; }
        public Nullable<int> Q_Take { get; set; }
        public Nullable<int> Q_A { get; set; }
        public Nullable<int> Q_NoofAttempts { get; set; }
    }
}
