//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waats.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int localId { get; set; }
        public string WaatsFormId { get; set; }
        public string Description { get; set; }
        public string CreationDate { get; set; }
    }
}
