//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waats.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class waatsForm
    {
        public int localID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string DoB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string GPName { get; set; }
        public string HistoryofMentalIllness { get; set; }
        public string ReferredtoMentalHealth { get; set; }
        public string HaveYouEverHadAnyThoughtsorMadeAttemptstoHarmYourself { get; set; }
        public string HaveYouCurrentlyorrecentlyAnyThoughtsorMadeAttemptstoHarmYourself { get; set; }
        public string HaveYouCurrentlyorrecentlyAnyThoughtsorMadeAttemptstoHarmAnyoneElse { get; set; }
        public string CompleteProjects { get; set; }
        public string RequiresOrganization { get; set; }
        public string keepAppointments { get; set; }
        public string StartTasksOnTime { get; set; }
        public string FidgetAndSquirm { get; set; }
        public string OverlyActiveAndCompelled { get; set; }
        public string MakeCarelessMistakes { get; set; }
        public string DifficultyKeepingMyAttention { get; set; }
        public string DifficultyConcentrating { get; set; }
        public string DifficultyFinding { get; set; }
        public string EasilyDistracted { get; set; }
        public string LeaveMySeatInMeetings { get; set; }
        public string DifficultyRelaxingOrUnwinding { get; set; }
        public string TalkingTooMuch { get; set; }
        public string FinishingTheSentences { get; set; }
        public string DifficultyWaitingMyTurn { get; set; }
        public string InterruptOtherPeople { get; set; }
        public string ReceiveWarningsAndPersistent { get; set; }
        public string DisciplinedOrAacked { get; set; }
        public string EverExperiencedABreakdown { get; set; }
        public string Completedby { get; set; }
        public string CompletionDate { get; set; }
        public string Action { get; set; }
        public string PracticeName { get; set; }
        public string Postcode { get; set; }
        public string Address { get; set; }
    }
}
